stages:
 - build
 - test
 - deploy   
variables:
 HOME_DIR: "/home/isysadmin/test-ci/"
 USER_DEPLOY: "isysadmin"
###
.BuildJSApp:
 stage: build
 script:
  - export TMP=$ENV
  - export pm2_config=${CI_PROJECT_NAME}.config.js
  - echo -e "cat <<EOT > \$pm2_config \n\$TMP\nEOT" > tmp.sh
  - sh tmp.sh
  - export DEST="${HOME_DIR}${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
  - export CURRENT="${HOME_DIR}${CI_PROJECT_NAME}/current"
  - sudo mkdir -p $DEST $CURRENT
  - sudo mv ${CI_PROJECT_NAME}.config.js $DEST
  - sudo cp -R * $DEST
  - sudo chown $USER_DEPLOY -R $DEST && sudo ln -s $DEST $CURRENT 
  - sudo su $USER_DEPLOY -c "cd $CURRENT && npm install && pm2 start ${CI_PROJECT_NAME}.config.js"

.OnlyProduction:
 only:
  - /^.*rc.*$/
 except:
  - branches

Node01Build:
 extends:
  - .BuildJSApp
  - .OnlyProduction
 tags:
  - stage-stak-ap-bs-dapp-api-1
  
Node02Build:
 extends:
  - .BuildJSApp
 tags:
  - stage-stak-ap-bs-dapp-api-2
