stages:
 - build
 - test
 - deploy   
variables:
 HOME_DIR: "/home/isysadmin/test-ci/"
 USER_DEPLOY: "isysadmin"
 
CreateConfig:
 stage: build
 script:
  - export TMP=$ENV
  - export pm2_config=${CI_PROJECT_NAME}.config.js
  - echo $TMP
  - echo -e "cat <<EOT > \$pm2_config \n\$TMP\nEOT" > tmp.sh
  - sh tmp.sh
  - cat ${CI_PROJECT_NAME}.config.js
 tags:
  - ssh
 
BuildJSApp:
 stage: build
 script:
  - export DEST="${HOME_DIR}${CI_PROJECT_NAME}"
  - echo $DEST
  - sudo mkdir -p $DEST
  - sudo cp -R * $DEST
  - sudo chown $USER_DEPLOY -R $DEST
  - sudo su $USER_DEPLOY -c "cd $DEST && npm install"
 tags:
  - ssh_
