stages:
 - build
 - test
 - deploy
 
variables:
 GIT_STRATEGY: none
 ANSIBLE_DIR: "/home/ubuntu/staking-iac/ansible"

stak-stage-ap-ms-dapp-api:
 stage: deploy
 script:
  - cd /home/ubuntu/staking-iac/ansible
  - sudo su ubuntu -c "ansible-playbook stak-stage-ap-ms-dapp-api.yml --extra-vars=\"node_git_version=${CI_COMMIT_TAG}\""
 only:
  - /^.*-ms-rc$/
 except:
  - branches
 tags:
  - stak-stage-ap-ms-bastion
  
PROD:
  stage: deploy
  script:
    - cd /home/ubuntu/staking-iac/ansible
    - sudo su ubuntu -c "ansible-playbook stak-prod-mp-ap-admin-api.yml --extra-vars=\"node_git_version=${CI_COMMIT_TAG}\""
  only:
    - master
  tags:
    - stak-prod-ms-mp-bastion

#   only:
#     - /^.*[0-9]$/
#   except:
#     - branches