stages:
 - build
 - test
 - deploy   
variables:
 HOME_DIR: "/home/isysadmin/test-ci/"
 USER_DEPLOY: "isysadmin"


BuildJSApp:
 stage: build
 script:
  - export DEST="${HOME_DIR}${CI_PROJECT_NAME}"
  - echo $DEST;id;whoami
  - sudo "mkdir -p $DEST;cp -R * $DEST;chown $USER_DEPLOY -R $DEST"
  - sudo su $USER_DEPLOY -c "cd $DEST && npm install"
 tags:
  - ssh