module.exports = {
  "REGISTER": "REGISTER",
  "FORGOT_PASSWORD": "FORGOT_PASSWORD",
  "TWOFA": "TWOFA",
  "UNSUBCRIBE": "UNSUBCRIBE",
  "KYC_AUTHENTICATION": "KYC_AUTHENTICATION",
  "TWOFA_MOBILE": "TWOFA_MOBILE",
}